const AWS = require('aws-sdk');
const ssm = new AWS.SSM({apiVersion: '2014-11-06'});

// params.json is generated by Terraform. Might be better to use
// object transformation in the cloudwatch rule target and pass
// those as part of the event?
const { prefix, DocumentName } = require('./params.json');

exports.handler = async (event) => {
  const parameter = event.detail.name;

  if (!parameter.startsWith(prefix)) {
    return {
      statusCode: 200,
      body: "Not my prefix not my problem"
    }
  }

  const trimPrefixRegex = new RegExp(`^${prefix}/`);
  const bareParameter = parameter.replace(trimPrefixRegex, '');

  const ssmSendCommandParameters = {
    DocumentName,
    Comment: `SSM parameter "${bareParameter}" updated`,
    Targets: [{
      Key: 'tag:ssm-path',
      Values: [ prefix ],
    }],
    TimeoutSeconds: 3600,
  };
  const result = await ssm.sendCommand(ssmSendCommandParameters).promise()

  const response = {
      statusCode: 200,
      body: result
  };

  return response;
};
